services:
  db:
    image: mysql:8.4.2
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quick_deal
    command: >
      mysqld --general-log=1 
              --general-log-file=/var/log/mysql/general-log.log 
              --innodb_print_all_deadlocks=1
              --log_error=/var/lib/mysql/error.log
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--bind", "0.0.0.0" ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    container_name: kafka
    image: apache/kafka:3.8.0
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka_data:/data
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://192.168.219.1:9092 # 애플리케이션 - 컨테이너
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:29093,EXTERNAL://:9092
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: 80EA1541-4E7E-49C0-B9AA-AD45FB2E6091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: unless-stopped
    container_name: kafka-ui
    ports:
      - '8081:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: Local-Kraft-Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: true
      KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: true
    depends_on:
      - kafka

#  quick-deal-api:
#    image: quick-deal-api:2409162007
#    container_name: quick-deal-api
#    ports:
#      - "8082:8082"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker  # Docker 프로파일 활성화, TODO: 나중에는 명령줄에서 설정할 것
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/quick_deal
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      SECRET_KEY: "localmysecretkeylocalmysecretkeylocalmysecretkeylocalmysecretkeylocalmysecretkey"
#    depends_on:
#      db:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#      kafka:
#        condition: service_started
volumes:
  kafka_data:
