server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quick_deal
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    sql-migration-suffixes: sql,ddl
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 10000ms

kafka:
  bootstrap-servers: localhost:9092

logging:
  level:
    com.quickdeal: DEBUG
  config: classpath:logback.xml

# 비즈니스 설정 값
jwt:
  secret-key: ${SECRET_KEY}

retry:
  delay: 1000 # 결제 페이지 접속 여부 확인 시 thread.sleep
  limit: 500 # 결제 페이지 접속 여부 반복 제한

queue:
  topic-header: "queue-"

payment:
  page:
    max-users: 100
    timeout-seconds: 600
